services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY
    volumes:
      - ../:/app
    command: streamlit run /app/app.py

  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: testing
    volumes:
      - ../:/app
    environment:
      - PYTHONPATH=/app/apps/todo
    command: >
      sh -c "cd apps/todo &&
      coverage run -m pytest tests/ &&
      coverage report -m &&
      coverage html"
