
services:
#  precommit:
  tests_ut:
    image: ${TESTS_IMAGE:?err}
    environment:
      - OPENAI_API_KEY
    volumes:
      - ${SOURCE_DIR:?err}:/usr/src/app
    command: >
      sh -c "coverage run -m pytest . --maxfail=3
      && coverage report
      && coverage html --fail-under=40
      || (echo ERROR Tests failed or Coverage under target! && exit 1)"

  app_run:
    image: ${TESTS_IMAGE:?err}
    environment:
      - OPENAI_API_KEY
      - ANONYMIZED_TELEMETRY
    volumes:
      - ${SOURCE_DIR:?err}:/usr/src/app
    command: python main.py

  app_ingest:
    image: ${TESTS_IMAGE:?err}
    environment:
      - OPENAI_API_KEY
      - ANONYMIZED_TELEMETRY
    volumes:
      - ${SOURCE_DIR:?err}:/usr/src/app
    command: python main.py --ingest
